# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/home/csmajs/pgoul002/final-project-awesome-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/home/csmajs/pgoul002/final-project-awesome-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/csmajs/pgoul002/final-project-awesome-game/CMakeFiles /data/home/csmajs/pgoul002/final-project-awesome-game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/csmajs/pgoul002/final-project-awesome-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AwesomeGame

# Build rule for target.
AwesomeGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AwesomeGame
.PHONY : AwesomeGame

# fast build rule for target.
AwesomeGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/build
.PHONY : AwesomeGame/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/abilities.o: src/abilities.cpp.o
.PHONY : src/abilities.o

# target to build an object file
src/abilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/abilities.cpp.o
.PHONY : src/abilities.cpp.o

src/abilities.i: src/abilities.cpp.i
.PHONY : src/abilities.i

# target to preprocess a source file
src/abilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/abilities.cpp.i
.PHONY : src/abilities.cpp.i

src/abilities.s: src/abilities.cpp.s
.PHONY : src/abilities.s

# target to generate assembly for a file
src/abilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/abilities.cpp.s
.PHONY : src/abilities.cpp.s

src/boss.o: src/boss.cpp.o
.PHONY : src/boss.o

# target to build an object file
src/boss.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/boss.cpp.o
.PHONY : src/boss.cpp.o

src/boss.i: src/boss.cpp.i
.PHONY : src/boss.i

# target to preprocess a source file
src/boss.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/boss.cpp.i
.PHONY : src/boss.cpp.i

src/boss.s: src/boss.cpp.s
.PHONY : src/boss.s

# target to generate assembly for a file
src/boss.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/boss.cpp.s
.PHONY : src/boss.cpp.s

src/character.o: src/character.cpp.o
.PHONY : src/character.o

# target to build an object file
src/character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/character.cpp.o
.PHONY : src/character.cpp.o

src/character.i: src/character.cpp.i
.PHONY : src/character.i

# target to preprocess a source file
src/character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/character.cpp.i
.PHONY : src/character.cpp.i

src/character.s: src/character.cpp.s
.PHONY : src/character.s

# target to generate assembly for a file
src/character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/character.cpp.s
.PHONY : src/character.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/playableCharacter.o: src/playableCharacter.cpp.o
.PHONY : src/playableCharacter.o

# target to build an object file
src/playableCharacter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/playableCharacter.cpp.o
.PHONY : src/playableCharacter.cpp.o

src/playableCharacter.i: src/playableCharacter.cpp.i
.PHONY : src/playableCharacter.i

# target to preprocess a source file
src/playableCharacter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/playableCharacter.cpp.i
.PHONY : src/playableCharacter.cpp.i

src/playableCharacter.s: src/playableCharacter.cpp.s
.PHONY : src/playableCharacter.s

# target to generate assembly for a file
src/playableCharacter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AwesomeGame.dir/build.make CMakeFiles/AwesomeGame.dir/src/playableCharacter.cpp.s
.PHONY : src/playableCharacter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AwesomeGame"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/abilities.o"
	@echo "... src/abilities.i"
	@echo "... src/abilities.s"
	@echo "... src/boss.o"
	@echo "... src/boss.i"
	@echo "... src/boss.s"
	@echo "... src/character.o"
	@echo "... src/character.i"
	@echo "... src/character.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/playableCharacter.o"
	@echo "... src/playableCharacter.i"
	@echo "... src/playableCharacter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

